import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseDocument, parseFrontmatterBlock, type Frontmatter } from "./frontmatter.ts";
import { lastCommitDate } from "./git.ts";

export const STATUSES = ["active", "idle", "cold", "promoted"] as const;
export type Status = (typeof STATUSES)[number];
export const SCHEMA_VERSION = 1;
export const RESERVED_SLUGS = [
  "capture", "c", "doctor", "help", "init", "install",
  "new", "set", "stale", "index", "post",
];
export const SLUG_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

export const JIG_ROOT = process.env.JIG_ROOT ?? resolve(dirname(fileURLToPath(import.meta.url)), "..", "..");
export const JIG_VERSION = readFileSync(join(JIG_ROOT, "VERSION"), "utf8").trim();

export function expandHome(p: string): string {
  if (p === "~") return homedir();
  if (p.startsWith("~/")) return join(homedir(), p.slice(2));
  return p;
}

export function workbenchHome(): string {
  return resolve(expandHome(process.env.WORKBENCH_HOME ?? "~/workbench"));
}

export function isWorkbench(dir: string): boolean {
  return existsSync(join(dir, ".workbench.yml"));
}

export function requireWorkbench(): string {
  const home = workbenchHome();
  if (!isWorkbench(home)) {
    fail(`${home} is not a workbench (no .workbench.yml). Run: wb-init ${home}`);
  }
  return home;
}

export function readConfig(home: string): Frontmatter {
  return parseFrontmatterBlock(readFileSync(join(home, ".workbench.yml"), "utf8"));
}

export function today(): string {
  const d = new Date();
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
}

export interface Entry {
  slug: string;
  dir: string;
  data: Frontmatter;
  body: string;
  error?: string;
}

export function entriesDir(home: string): string {
  return join(home, "entries");
}

export function listSlugs(home: string): string[] {
  const dir = entriesDir(home);
  if (!existsSync(dir)) return [];
  return readdirSync(dir)
    .filter((n) => !n.startsWith(".") && statSync(join(dir, n)).isDirectory())
    .sort();
}

export function readEntry(home: string, slug: string): Entry {
  const dir = join(entriesDir(home), slug);
  const readme = join(dir, "README.md");
  if (!existsSync(readme)) return { slug, dir, data: {}, body: "", error: "missing README.md" };
  try {
    const { data, body } = parseDocument(readFileSync(readme, "utf8"));
    return { slug, dir, data, body };
  } catch (e) {
    return { slug, dir, data: {}, body: "", error: (e as Error).message };
  }
}

export function listEntries(home: string): Entry[] {
  return listSlugs(home).map((s) => readEntry(home, s));
}

export function validateEntry(e: Entry): string[] {
  const problems: string[] = [];
  if (e.error) return [e.error];
  const d = e.data;
  if (d.id !== e.slug) problems.push(`id "${String(d.id)}" does not match directory "${e.slug}"`);
  if (typeof d.title !== "string" || d.title === "") problems.push("missing title");
  if (!STATUSES.includes(d.status as Status)) problems.push(`invalid status "${String(d.status)}"`);
  const outcome = d.outcome ?? "";
  if ((d.status === "cold" || d.status === "promoted") && (outcome === "" || outcome === null)) {
    problems.push(`status ${String(d.status)} requires an outcome`);
  }
  if ((d.status === "active" || d.status === "idle") && outcome !== "" && outcome !== null) {
    problems.push(`status ${String(d.status)} must have an empty outcome`);
  }
  if (typeof d.created !== "string" || !/^\d{4}-\d{2}-\d{2}$/.test(d.created)) problems.push("created must be YYYY-MM-DD");
  if (d.schema_version !== SCHEMA_VERSION) problems.push(`schema_version must be ${SCHEMA_VERSION}`);
  if (d.tags !== undefined && !Array.isArray(d.tags)) problems.push("tags must be a list");
  return problems;
}

export function lastTouched(home: string, e: Entry): string {
  const iso = lastCommitDate(home, `entries/${e.slug}`);
  if (iso) return iso.slice(0, 10);
  return typeof e.data.created === "string" ? e.data.created : "unknown";
}

export function readTemplate(name: string): string {
  return readFileSync(join(JIG_ROOT, "templates", name), "utf8");
}

export function renderIndex(home: string): string {
  const entries = listEntries(home).filter((e) => !e.error);
  const touched = new Map(entries.map((e) => [e.slug, lastTouched(home, e)]));
  const lines: string[] = [
    "<!-- Generated by wb-index. Do not edit. Run wb-index to refresh. -->",
    "",
    "# Index",
    "",
  ];
  for (const status of ["active", "idle", "promoted", "cold"] as const) {
    const group = entries
      .filter((e) => e.data.status === status)
      .sort((a, b) => (touched.get(b.slug) ?? "").localeCompare(touched.get(a.slug) ?? "") || a.slug.localeCompare(b.slug));
    if (group.length === 0) continue;
    lines.push(`## ${status[0].toUpperCase()}${status.slice(1)}`, "");
    for (const e of group) {
      const premise = typeof e.data.premise === "string" && e.data.premise !== "" ? `: ${e.data.premise}` : "";
      lines.push(`- [${String(e.data.title)}](entries/${e.slug}/README.md)${premise} (${touched.get(e.slug)})`);
    }
    lines.push("");
  }
  if (entries.length === 0) lines.push("No entries yet. Run `wb-new <slug> [title]`.", "");
  return lines.join("\n");
}

export function writeIndex(home: string): string {
  const content = renderIndex(home);
  writeFileSync(join(home, "INDEX.md"), content);
  return content;
}

export function appendLog(home: string, slug: string, line: string): void {
  const path = join(entriesDir(home), slug, "log.md");
  const existing = existsSync(path) ? readFileSync(path, "utf8") : "";
  const sep = existing === "" || existing.endsWith("\n") ? "" : "\n";
  writeFileSync(path, `${existing}${sep}- ${today()}: ${line.trim()}\n`);
}

export const MANAGED_START = "<!-- wb:managed:start -->";
export const MANAGED_END = "<!-- wb:managed:end -->";

export function managedBlock(): string {
  const t = readTemplate("AGENTS.md");
  const s = t.indexOf(MANAGED_START);
  const e = t.indexOf(MANAGED_END);
  if (s === -1 || e === -1) throw new Error("templates/AGENTS.md is missing managed markers");
  return t.slice(s, e + MANAGED_END.length);
}

export function refreshManagedBlock(content: string): string {
  const s = content.indexOf(MANAGED_START);
  const e = content.indexOf(MANAGED_END);
  if (s === -1 || e === -1) return `${managedBlock()}\n\n${content}`;
  return content.slice(0, s) + managedBlock() + content.slice(e + MANAGED_END.length);
}

export function fail(msg: string, code = 1): never {
  process.stderr.write(`wb: ${msg}\n`);
  process.exit(code);
}

export function warn(msg: string): void {
  process.stderr.write(`wb: warning: ${msg}\n`);
}

export function closeMatches(slug: string, slugs: string[]): string[] {
  const lower = slug.toLowerCase();
  const hits = slugs.filter((s) => s.includes(lower) || lower.includes(s));
  if (hits.length > 0) return hits;
  return slugs.filter((s) => levenshtein(s, lower) <= Math.max(2, Math.floor(lower.length / 3)));
}

function levenshtein(a: string, b: string): number {
  const prev = Array.from({ length: b.length + 1 }, (_, i) => i);
  for (let i = 1; i <= a.length; i++) {
    let last = prev[0];
    prev[0] = i;
    for (let j = 1; j <= b.length; j++) {
      const tmp = prev[j];
      prev[j] = Math.min(prev[j] + 1, prev[j - 1] + 1, last + (a[i - 1] === b[j - 1] ? 0 : 1));
      last = tmp;
    }
  }
  return prev[b.length];
}
