import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import {
  RESERVED_SLUGS, SLUG_RE, closeMatches, readEntry, refreshManagedBlock, renderIndex, validateEntry,
} from "../src/lib/workbench.ts";

function makeHome(): string {
  const home = mkdtempSync(join(tmpdir(), "jig-test-"));
  mkdirSync(join(home, "entries"), { recursive: true });
  writeFileSync(join(home, ".workbench.yml"), "name: t\nschema_version: 1\njig_version: 0.0.0\n");
  return home;
}

function addEntry(home: string, slug: string, fm: string): void {
  mkdirSync(join(home, "entries", slug), { recursive: true });
  writeFileSync(join(home, "entries", slug, "README.md"), `---\n${fm}\n---\n\n## Premise\n`);
}

test("slug rules", () => {
  for (const s of ["a", "spades-game", "v2-api"]) assert.ok(SLUG_RE.test(s), s);
  for (const s of ["", "Spades", "a--b", "-a", "a-", "a_b", "a b"]) assert.ok(!SLUG_RE.test(s), s);
  for (const s of ["capture", "doctor", "help", "init", "install"]) assert.ok(RESERVED_SLUGS.includes(s), s);
});

test("validateEntry enforces status and outcome rules", () => {
  const home = makeHome();
  try {
    addEntry(home, "ok", "id: ok\ntitle: Ok\nstatus: active\ncreated: 2026-09-20\noutcome: \"\"\nschema_version: 1");
    addEntry(home, "cold-no-reason", "id: cold-no-reason\ntitle: C\nstatus: cold\ncreated: 2026-09-20\noutcome: \"\"\nschema_version: 1");
    addEntry(home, "wrong-id", "id: other\ntitle: W\nstatus: bogus\ncreated: 2026-9-20\nschema_version: 2");
    assert.deepEqual(validateEntry(readEntry(home, "ok")), []);
    assert.match(validateEntry(readEntry(home, "cold-no-reason")).join(";"), /requires an outcome/);
    const problems = validateEntry(readEntry(home, "wrong-id"));
    assert.equal(problems.length, 4, problems.join("; "));
  } finally {
    rmSync(home, { recursive: true, force: true });
  }
});

test("renderIndex groups by status in fixed order and falls back to created date", () => {
  const home = makeHome();
  try {
    addEntry(home, "b-cold", "id: b-cold\ntitle: B\nstatus: cold\npremise: old\ncreated: 2026-01-01\noutcome: done\nschema_version: 1");
    addEntry(home, "a-active", "id: a-active\ntitle: A\nstatus: active\npremise: fresh\ncreated: 2026-09-20\noutcome: \"\"\nschema_version: 1");
    const out = renderIndex(home);
    assert.ok(out.startsWith("<!-- Generated by wb-index"));
    assert.ok(out.indexOf("## Active") < out.indexOf("## Cold"));
    assert.match(out, /- \[A\]\(entries\/a-active\/README\.md\): fresh \(2026-09-20\)/);
  } finally {
    rmSync(home, { recursive: true, force: true });
  }
});

test("refreshManagedBlock keeps local notes and replaces the block", () => {
  const stale = "<!-- wb:managed:start -->\nold\n<!-- wb:managed:end -->\n\n## Local notes\nkeep me\n";
  const out = refreshManagedBlock(stale);
  assert.ok(out.includes("# Workbench rules"));
  assert.ok(!out.includes("\nold\n"));
  assert.ok(out.endsWith("## Local notes\nkeep me\n"));
  assert.ok(refreshManagedBlock("no block").endsWith("\n\nno block"));
});

test("closeMatches finds substrings then near misses", () => {
  const slugs = ["spades-game", "spade-tool", "zzz"];
  assert.deepEqual(closeMatches("spade", slugs), ["spades-game", "spade-tool"]);
  assert.deepEqual(closeMatches("zzy", slugs), ["zzz"]);
  assert.deepEqual(closeMatches("qqqqqqqq", slugs), []);
});
